CSUB-988 CC3 Staking Dashboard: Nominate from favorites shows empty list
gluwa/creditcoin3-staking-dashboard pull request #58
Opened 2024-01-05 16:38 UTC by frankli-dev

2024-01-09 10:28 UTC, atodorov approved these changes
I can confirm that this PR allows me to nominate validators which I've previously marked as favorites!

2024-01-09 10:28 UTC, atodorov requested changes
Needs rebase to resolve MegaLinter failures!

2024-01-10 14:23 UTC, atodorov approved these changes

2024-01-10 18:35 UTC, pLabarta approved these changes

2024-01-10 20:31 UTC, merged